### ISSUE TITLE
TRACK COMPLETE button does not work

### ISSUE THREAD

**Issue by fsultani** [learn-co-curriculum/bash-navigation-nitrous#11]
https://learn.co/tracks/intro-to-learn-nitrous/intro-to-learn-nitrous/using-a-shell/navigating-with-bash

**Comment by AnnJohn** [comment]
Hi @fsultani sorry for the issue you're having. This looks like a bug, so if you could file a bug report that would be great. If you hover over your profile pic in Learn, you'll see an option to Report a Bug. 

Also since it looks like you need immediate help with this, you can also use the Ask a Question tool in Learn and someone from our support team will get back to you right away. Thanks!
